name: CI/CD pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  # --- CI job: build & push image ---
  build:
    runs-on: self-hosted
    outputs:
      tag: ${{ steps.vars.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s:${{ steps.vars.outputs.TAG }}

  # --- CD job: deploy with Helm ---
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.3"

      - name: Install helm
        uses: azure/setup-helm@v4
        with:
          version: "v3.15.2"

      - name: Write kubeconfig
        run: echo "$KUBECONFIG_B64" | base64 -d > kubeconfig
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Helm upgrade
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          helm upgrade --install hello-k8s ./hello-k8s -n demo \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s \
            --set image.tag=${{ needs.build.outputs.tag }}
