name: CI/CD pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  # --- CI job: build & push image ---
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s:${{ steps.vars.outputs.TAG }}

  # --- CD job: deploy with Helm ---
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write kubeconfig
        run: |
          $env:KUBECONFIG="${{ github.workspace }}\kubeconfig"
          [System.Text.Encoding]::UTF8.GetString(
            [System.Convert]::FromBase64String("${{ secrets.KUBECONFIG_DATA }}")
          ) | Out-File -FilePath $env:KUBECONFIG -Encoding utf8
          
      - name: Deploy with Helm
        run: |
          $env:KUBECONFIG="${{ github.workspace }}\kubeconfig"
          kubectl config view
          kubectl get nodes
          helm upgrade --install hello-k8s . -n demo --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s --set image.tag=${{ needs.build.outputs.tag }}
